name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change this if your branch name is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Match the Ruby version used in your Jekyll project

      - name: Install Bundler
        run: gem install bundler

      - name: Cache Bundler Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3 --verbose

      - name: Check _site directory
        run: ls -l _site || echo "_site directory does not exist"

      - name: Build Jekyll Site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Upload Jekyll site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: _site/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Jekyll site artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: _site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site/
          force_orphan: true  # Ensures a clean deployment
